[package]
name = "hc_facets"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_facets"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

hc_facets_integrity = { workspace = true } 
